import Foundation
import PersonaPlex   // reuse MimiConfig, SeanetConfig, MimiTransformerConfig, PadMode

// MARK: - Top-level Configuration

public struct HibikiConfig: Sendable {
    public var temporal: HibikiTemporalConfig
    public var depformer: HibikiDepformerConfig
    public var mimi: MimiConfig
    public var sampling: HibikiSamplingConfig
    public var delays: [Int]
    public var languages: HibikiLanguages
    public var sampleRate: Int

    public init(
        temporal: HibikiTemporalConfig = .zero3B,
        depformer: HibikiDepformerConfig = .zero3B,
        mimi: MimiConfig = .moshiko(numCodebooks: 16),
        sampling: HibikiSamplingConfig = .default,
        delays: [Int] = HibikiConfig.zero3BDelays,
        languages: HibikiLanguages = .zero3B,
        sampleRate: Int = 24000
    ) {
        self.temporal = temporal
        self.depformer = depformer
        self.mimi = mimi
        self.sampling = sampling
        self.delays = delays
        self.languages = languages
        self.sampleRate = sampleRate
    }

    /// Number of streams: 1 text + nQ source audio + nQ target audio.
    /// For Zero-3B: 1 + 16 + 16 = 33.
    public var numStreams: Int { 1 + 2 * temporal.nQ }

    /// Number of source-side audio codebooks (input, fed via Mimi encode).
    public var numSourceCodebooks: Int { temporal.nQ }

    /// Number of target-side audio codebooks (output, generated by depformer).
    /// For Hibiki this equals `dep_q == nQ`.
    public var numTargetCodebooks: Int { depformer.numSteps }

    /// Maximum delay across all streams. For Zero-3B: 2.
    public var maxDelay: Int { delays.max() ?? 0 }

    /// Hibiki Zero-3B preset: FR/ES/PT/DE → EN, no conditioner, GQA temporal,
    /// rope_concat, scheduled MultiLinear depformer, no low-rank embeddings.
    public static var zero3B: HibikiConfig {
        HibikiConfig(
            temporal: .zero3B,
            depformer: .zero3B,
            mimi: .moshiko(numCodebooks: 16),
            sampling: .default,
            delays: zero3BDelays,
            languages: .zero3B,
            sampleRate: 24000
        )
    }

    /// 33 entries: text + 16 source + 16 target. Source cb0 / target cb0 use
    /// delay=0 (semantic), all other codebooks use delay=2 (acoustic).
    public static let zero3BDelays: [Int] = (
        [0]
        + [0] + Array(repeating: 2, count: 15)   // source: cb0 + cb1..15
        + [0] + Array(repeating: 2, count: 15)   // target: cb0 + cb1..15
    )
}

// MARK: - Temporal Transformer Config

public struct HibikiTemporalConfig: Sendable {
    public var dim: Int
    public var numLayers: Int
    public var numHeads: Int
    public var hiddenScale: Float
    public var nQ: Int                     // codebooks per side (16 for Zero-3B)
    public var card: Int                   // audio vocab (2048)
    public var textCard: Int               // text vocab (48000)
    public var context: Int
    public var maxPeriod: Float
    public var rmsNormEps: Float
    public var groupSize: Int
    public var bits: Int
    public var kvRepeat: Int               // GQA: numHeads / kvRepeat = numKVHeads
    public var positionalEmbedding: HibikiPositionalEmbedding

    /// FFN intermediate size: LLaMA-style formula `dim * 2/3 * hiddenScale`.
    /// For Zero-3B: 2048 * 2/3 * 6 ≈ 8192.
    public var intermediateSize: Int { Int(Float(dim) * 2.0 / 3.0 * hiddenScale) }

    /// Per-head dimension. For Zero-3B: 2048 / 16 = 128.
    public var headDim: Int { dim / numHeads }

    /// GQA: number of key/value heads. For Zero-3B: 16 / 2 = 8.
    public var numKVHeads: Int { numHeads / kvRepeat }

    /// GQA: total KV feature width. For Zero-3B: 8 * 128 = 1024.
    public var kvDim: Int { numKVHeads * headDim }

    /// Number of audio embedding tables: nQ source + nQ target.
    /// For Zero-3B: 32.
    public var numAudioEmbeddings: Int { 2 * nQ }

    /// Total streams: 1 text + 2*nQ audio. For Zero-3B: 33.
    public var numCodebooks: Int { 1 + numAudioEmbeddings }

    /// Initial token id for audio (= card, one past valid range).
    public var initialTokenId: Int { card }

    /// Initial token id for text (= textCard).
    public var textInitialTokenId: Int { textCard }

    /// Padding token id used by SPM-48k tokenizer.
    /// Matches `existing_text_padding_id: 3` in upstream config.
    public var textPaddingId: Int { 3 }

    public init(
        dim: Int = 2048,
        numLayers: Int = 28,
        numHeads: Int = 16,
        hiddenScale: Float = 6.0,
        nQ: Int = 16,
        card: Int = 2048,
        textCard: Int = 48000,
        context: Int = 3000,
        maxPeriod: Float = 20000,
        rmsNormEps: Float = 1e-8,
        groupSize: Int = 64,
        bits: Int = 4,
        kvRepeat: Int = 2,
        positionalEmbedding: HibikiPositionalEmbedding = .ropeConcat
    ) {
        self.dim = dim
        self.numLayers = numLayers
        self.numHeads = numHeads
        self.hiddenScale = hiddenScale
        self.nQ = nQ
        self.card = card
        self.textCard = textCard
        self.context = context
        self.maxPeriod = maxPeriod
        self.rmsNormEps = rmsNormEps
        self.groupSize = groupSize
        self.bits = bits
        self.kvRepeat = kvRepeat
        self.positionalEmbedding = positionalEmbedding
    }

    public static var zero3B: HibikiTemporalConfig { HibikiTemporalConfig() }
}

// MARK: - Positional Embedding

/// Positional encoding selector for the temporal transformer.
///
/// - `rope`: standard interleaved RoPE (used by Hibiki 1B/2B and PersonaPlex/Moshi).
/// - `ropeConcat`: split-half RoPE (used by Hibiki Zero-3B). Real and imaginary
///   halves are stored contiguously: `[r..., i...]`.
///
/// Mapping to mlx-swift's `RoPE(traditional:)`:
/// - mlx-swift `traditional: true` rotates consecutive pairs `(r0, i0, r1, i1, ...)`.
///   This corresponds to Kyutai's `apply_rope(interleave=True)`.
/// - mlx-swift `traditional: false` (default) rotates with stride half — i.e. the
///   "standard" GPT-NeoX / LLaMA style. This corresponds to Kyutai's `apply_rope(interleave=False)`.
///
/// Empirically, **PersonaPlex** uses `traditional: true` for `rope` so the
/// `traditional` flag for plain `rope` here matches PersonaPlex. For `ropeConcat`
/// (Kyutai `interleave=False`) we use `traditional: false`.
public enum HibikiPositionalEmbedding: String, Sendable, Codable {
    case rope
    case ropeConcat = "rope_concat"

    /// Maps to mlx-swift's `traditional` flag.
    public var traditional: Bool {
        switch self {
        case .rope:        return true
        case .ropeConcat:  return false
        }
    }
}

// MARK: - Depformer Config

public struct HibikiDepformerConfig: Sendable {
    public var dim: Int
    public var numLayers: Int
    public var numHeads: Int
    public var dimFeedforward: Int
    /// Number of generation steps per temporal frame (= dep_q = number of target
    /// codebooks generated per frame). For Zero-3B: 16.
    public var numSteps: Int
    public var card: Int
    public var textCard: Int
    public var context: Int
    public var rmsNormEps: Float
    public var weightsPerStep: Bool
    public var multiLinear: Bool
    public var groupSize: Int
    public var bits: Int
    public var kvRepeat: Int

    /// Maps generation step → unique slice index for MultiLinear weights.
    /// For Zero-3B: `[0,1,2,3,4,5,6,7,8,8,8,8,8,8,8,8]` — 9 unique slices.
    /// For PersonaPlex / unscheduled depformer: `nil` (each step has its own slice).
    public var weightsPerStepSchedule: [Int]?

    /// Number of unique slice weights stored. Equals `(max(schedule) + 1)` when
    /// scheduled, otherwise equals `numSteps`.
    public var numUniqueSlices: Int {
        if let s = weightsPerStepSchedule, !s.isEmpty {
            return (s.max() ?? (numSteps - 1)) + 1
        }
        return numSteps
    }

    /// Slice index for a given generation step.
    public func sliceIndex(forStep step: Int) -> Int {
        if let s = weightsPerStepSchedule, step < s.count {
            return s[step]
        }
        return step
    }

    /// Per-head dimension. For Zero-3B: 1024 / 16 = 64.
    public var headDim: Int { dim / numHeads }

    /// GQA in depformer (1 = MHA). Hibiki Zero-3B uses MHA in depformer.
    public var numKVHeads: Int { numHeads / kvRepeat }

    public init(
        dim: Int = 1024,
        numLayers: Int = 6,
        numHeads: Int = 16,
        dimFeedforward: Int = 4096,    // = depformer.dim * 2/3 * temporal.hiddenScale = 1024*2/3*6
        numSteps: Int = 16,            // dep_q for Zero-3B
        card: Int = 2048,
        textCard: Int = 48000,
        context: Int = 16,
        rmsNormEps: Float = 1e-8,
        weightsPerStep: Bool = true,
        multiLinear: Bool = true,
        groupSize: Int = 64,
        bits: Int = 4,
        kvRepeat: Int = 1,
        weightsPerStepSchedule: [Int]? = HibikiDepformerConfig.zero3BSchedule
    ) {
        self.dim = dim
        self.numLayers = numLayers
        self.numHeads = numHeads
        self.dimFeedforward = dimFeedforward
        self.numSteps = numSteps
        self.card = card
        self.textCard = textCard
        self.context = context
        self.rmsNormEps = rmsNormEps
        self.weightsPerStep = weightsPerStep
        self.multiLinear = multiLinear
        self.groupSize = groupSize
        self.bits = bits
        self.kvRepeat = kvRepeat
        self.weightsPerStepSchedule = weightsPerStepSchedule
    }

    /// Hibiki 2B / Zero-3B schedule: 9 unique slices over 16 steps.
    /// Steps 0..7 each have unique slice; steps 8..15 all share slice 8.
    public static let zero3BSchedule: [Int] = [
        0, 1, 2, 3, 4, 5, 6, 7, 8,
        8, 8, 8, 8, 8, 8, 8,
    ]

    public static var zero3B: HibikiDepformerConfig { HibikiDepformerConfig() }
}

// MARK: - Sampling Config

public struct HibikiSamplingConfig: Sendable {
    public var audioTemp: Float
    public var audioTopK: Int
    public var textTemp: Float
    public var textTopK: Int
    public var audioRepetitionPenalty: Float
    public var textRepetitionPenalty: Float
    public var repetitionWindow: Int

    public init(
        audioTemp: Float = 0.8,
        audioTopK: Int = 250,
        textTemp: Float = 0.8,
        textTopK: Int = 250,
        audioRepetitionPenalty: Float = 1.0,
        textRepetitionPenalty: Float = 1.0,
        repetitionWindow: Int = 0
    ) {
        self.audioTemp = audioTemp
        self.audioTopK = audioTopK
        self.textTemp = textTemp
        self.textTopK = textTopK
        self.audioRepetitionPenalty = audioRepetitionPenalty
        self.textRepetitionPenalty = textRepetitionPenalty
        self.repetitionWindow = repetitionWindow
    }

    public static var `default`: HibikiSamplingConfig { HibikiSamplingConfig() }
}

// MARK: - Languages

public struct HibikiLanguages: Sendable {
    public var source: [HibikiSourceLanguage]
    public var target: HibikiTargetLanguage

    public init(source: [HibikiSourceLanguage], target: HibikiTargetLanguage) {
        self.source = source
        self.target = target
    }

    public static let zero3B = HibikiLanguages(
        source: [.fr, .es, .pt, .de], target: .en
    )
}

public enum HibikiSourceLanguage: String, CaseIterable, Sendable, Codable {
    case fr
    case es
    case pt
    case de

    public var displayName: String {
        switch self {
        case .fr: return "French"
        case .es: return "Spanish"
        case .pt: return "Portuguese"
        case .de: return "German"
        }
    }
}

public enum HibikiTargetLanguage: String, CaseIterable, Sendable, Codable {
    case en

    public var displayName: String {
        switch self {
        case .en: return "English"
        }
    }
}

// MARK: - JSON loader (matches converter output)

public extension HibikiConfig {
    /// Load a `HibikiConfig` from a `config.json` file produced by
    /// `models/hibiki/export/convert.py --variant 3b-zero`.
    static func load(from url: URL) throws -> HibikiConfig {
        let data = try Data(contentsOf: url)
        let raw = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        guard let raw else {
            throw HibikiConfigError.invalidJSON("root is not an object")
        }

        let temporalRaw = (raw["temporal"] as? [String: Any]) ?? [:]
        let depformerRaw = (raw["depformer"] as? [String: Any]) ?? [:]
        let langsRaw = (raw["languages"] as? [String: Any]) ?? [:]
        let quantRaw = (raw["quantization"] as? [String: Any]) ?? [:]

        let bits = (quantRaw["bits"] as? Int) ?? 4
        let groupSize = (quantRaw["group_size"] as? Int) ?? 64

        let temporal = HibikiTemporalConfig(
            dim: (temporalRaw["dim"] as? Int) ?? 2048,
            numLayers: (temporalRaw["num_layers"] as? Int) ?? 28,
            numHeads: (temporalRaw["num_heads"] as? Int) ?? 16,
            hiddenScale: Float((temporalRaw["hidden_scale"] as? Double) ?? 6.0),
            nQ: ((temporalRaw["n_q"] as? Int) ?? 32) / 2,    // n_q is total (src+tgt)
            card: (temporalRaw["card"] as? Int) ?? 2048,
            textCard: (temporalRaw["text_card"] as? Int) ?? 48000,
            context: (temporalRaw["context"] as? Int) ?? 3000,
            maxPeriod: Float((temporalRaw["max_period"] as? Double) ?? 20000),
            groupSize: groupSize,
            bits: bits,
            kvRepeat: (temporalRaw["kv_repeat"] as? Int) ?? 2,
            positionalEmbedding: HibikiPositionalEmbedding(
                rawValue: (temporalRaw["positional_embedding"] as? String) ?? "rope_concat"
            ) ?? .ropeConcat
        )

        let dimFf: Int = {
            if let v = depformerRaw["dim_feedforward"] as? Int { return v }
            // null in source — derive from depformer.dim * 2/3 * temporal.hiddenScale
            let d = (depformerRaw["dim"] as? Int) ?? 1024
            return Int(Float(d) * 2.0 / 3.0 * temporal.hiddenScale)
        }()

        let depformer = HibikiDepformerConfig(
            dim: (depformerRaw["dim"] as? Int) ?? 1024,
            numLayers: (depformerRaw["num_layers"] as? Int) ?? 6,
            numHeads: (depformerRaw["num_heads"] as? Int) ?? 16,
            dimFeedforward: dimFf,
            numSteps: (depformerRaw["num_steps"] as? Int) ?? 16,
            card: (depformerRaw["card"] as? Int) ?? 2048,
            textCard: (depformerRaw["text_card"] as? Int) ?? 48000,
            context: (depformerRaw["context"] as? Int) ?? 16,
            weightsPerStep: (depformerRaw["weights_per_step"] as? Bool) ?? true,
            multiLinear: (depformerRaw["multi_linear"] as? Bool) ?? true,
            groupSize: groupSize,
            bits: bits,
            kvRepeat: (depformerRaw["kv_repeat"] as? Int) ?? 1,
            weightsPerStepSchedule: depformerRaw["weights_per_step_schedule"] as? [Int]
        )

        let delays = (raw["delays"] as? [Int]) ?? HibikiConfig.zero3BDelays

        let sources: [HibikiSourceLanguage] = {
            guard let arr = langsRaw["source"] as? [String] else {
                return [.fr, .es, .pt, .de]
            }
            return arr.compactMap { HibikiSourceLanguage(rawValue: $0) }
        }()
        let target = (langsRaw["target"] as? String).flatMap {
            HibikiTargetLanguage(rawValue: $0)
        } ?? .en

        return HibikiConfig(
            temporal: temporal,
            depformer: depformer,
            mimi: .moshiko(numCodebooks: temporal.nQ),
            sampling: .default,
            delays: delays,
            languages: HibikiLanguages(source: sources, target: target),
            sampleRate: 24000
        )
    }
}

public enum HibikiConfigError: Error, CustomStringConvertible {
    case invalidJSON(String)

    public var description: String {
        switch self {
        case .invalidJSON(let msg): return "HibikiConfig invalid JSON: \(msg)"
        }
    }
}
