#!/usr/bin/env python3
"""SentencePiece parity check for Nemotron word-boosting tokenization.

Tokenizes a small phrase corpus with Python `sentencepiece` (the canonical
reference) and the Swift `NemotronSentencePieceUnigramTokenizer` (via the
`speech` CLI's hidden `--print-spm-tokenization` flag — wired only for this
parity script). Diffs the two outputs and exits non-zero on any divergence.

Run this whenever the Nemotron tokenizer.model bundle changes, to catch
normalization drift (NFKC, control-char stripping, whitespace marker) that
silently breaks word boosting on OOV terms.

Usage:
    pip install sentencepiece
    python scripts/nemotron_spm_parity.py \
        --tokenizer ~/Library/Caches/qwen3-speech/models/aufklarer/Nemotron-3.5-ASR-Streaming-0.6B-CoreML-INT8/tokenizer.model \
        --phrases scripts/nemotron_spm_parity_phrases.txt

If --phrases is omitted, a small built-in corpus is used (the same phrases
the hard-coded WordBoostingTokenizerTests assertion exercises plus a
spread of names / acronyms / fragmented OOV terms).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable

try:
    import sentencepiece as spm  # type: ignore[import-not-found]
except ImportError:
    print(
        "error: `sentencepiece` is not installed.\n"
        "  pip install sentencepiece",
        file=sys.stderr,
    )
    raise SystemExit(2)


DEFAULT_PHRASES: list[str] = [
    # Hard-coded assertion fixtures (kept in sync with WordBoostingTests).
    "Voxtral",
    "voxtral",
    "Babble",
    "vocab JSON",
    "should",
    # Brand / acronym short forms.
    "AI", "iOS", "kHz", "EU", "Qi",
    # Names that fragment under SPM.
    "Aoife",
    "Siobhan",
    "Niamh",
    # Multi-token technical terms.
    "Kubernetes",
    "PostgreSQL",
    "rsync",
    "NVMe",
    # Phrases with mixed casing / punctuation that should round-trip.
    "macOS Sonoma",
    "Apple Silicon",
    "Half-Life 2",
    # Phrases that should agree even with the greedy fallback.
    "hello world",
    "how are you",
]


def phrase_to_pieces(s: str) -> str:
    """Apply the Swift tokenizer's pre-tokenization (NFKC, collapse whitespace,
    leading word-boundary marker, internal spaces → ▁)."""
    import unicodedata
    norm = unicodedata.normalize("NFKC", s)
    collapsed = " ".join(norm.split())
    if not collapsed:
        return ""
    return "▁" + collapsed.replace(" ", "▁")


def encode_with_spm(model_path: Path, phrases: Iterable[str]) -> list[list[int]]:
    sp = spm.SentencePieceProcessor()
    sp.Load(str(model_path))
    out: list[list[int]] = []
    for phrase in phrases:
        pieces = phrase_to_pieces(phrase)
        if not pieces:
            out.append([])
            continue
        # Encode the pre-tokenized form directly so we exercise the same
        # Viterbi DP path the Swift impl uses (no second pass through SPM's
        # own pre-tokenizer).
        out.append(sp.EncodeAsIds(pieces))
    return out


def write_swift_fixture(json_path: Path, phrases: list[str], ids: list[list[int]]) -> None:
    """Write a JSON fixture the Swift parity test consumes."""
    payload = {
        "phrases": [
            {"phrase": p, "expected": eids}
            for p, eids in zip(phrases, ids)
        ],
        "note": "Generated by scripts/nemotron_spm_parity.py — regenerate when tokenizer.model changes.",
    }
    json_path.write_text(json.dumps(payload, indent=2))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tokenizer", required=True, type=Path,
                        help="Path to tokenizer.model")
    parser.add_argument("--phrases", type=Path,
                        help="Optional newline-delimited phrase file (default: built-in corpus)")
    parser.add_argument("--write-fixture", type=Path,
                        help="Optional path to dump the resulting (phrase, ids) JSON for use as a Swift test fixture")
    args = parser.parse_args()

    if not args.tokenizer.exists():
        print(f"error: tokenizer not found at {args.tokenizer}", file=sys.stderr)
        return 2

    if args.phrases:
        phrases = [
            line.strip()
            for line in args.phrases.read_text().splitlines()
            if line.strip() and not line.startswith("#")
        ]
    else:
        phrases = DEFAULT_PHRASES

    ids = encode_with_spm(args.tokenizer, phrases)

    for phrase, eids in zip(phrases, ids):
        print(f"  {phrase!r:30s} → {eids}")

    if args.write_fixture:
        write_swift_fixture(args.write_fixture, phrases, ids)
        print(f"\nWrote {len(phrases)} entries → {args.write_fixture}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
